name             'openscap'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures openscap'
long_description 'Installs/Configures openscap'
version          '0.1.0'

depends 'apt'
depends 'git'
depends 'build-essential'
depends 'python'